WebProgramalamaProje/WebProgramalamaProje/Controllers/TownController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebProgramalamaProje.Data;
using WebProgramalamaProje.Models;

namespace WebProgramalamaProje.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TownController : Controller
    {
        private readonly ApplicationDbContext _db;

        public TownController(ApplicationDbContext db)
        {
            _db = db;
        }
        
        public async Task<IActionResult> Index()
        {
            var model = await _db.Towns.ToListAsync();
            return View(model);
        }

        [HttpPost]
       
        public async Task<IActionResult> List()//not using now
        {
            return View();
        }
        
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        
        public async Task<IActionResult> Create(TownModel model)
        {
            if(ModelState.IsValid)
            {
                await _db.Towns.AddAsync(model);
                await _db.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View();
        }
        
        public async Task<IActionResult> Edit(int id)
        {
            var model=await _db.Towns.FindAsync(id);

            if(model!=null)
                return View(model);

            return RedirectToAction("Index");
        }

        [HttpPost]
       
        public async Task<IActionResult> Edit(TownModel model)
        {
            if(ModelState.IsValid)
            {
                _db.Towns.Update(model);
                await _db.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View(model);
        }
        

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var model = await _db.Towns.FindAsync(id);
            if (model != null)
            {
                _db.Towns.Remove(model);
                await _db.SaveChangesAsync();

                return Json(new { success = true, deletedId = id });
            }
            return Json(new { error = true });
        }
    }
}

WebProgramalamaProje/WebProgramalamaProje/Views/Town/Create.cshtml
@model WebProgramalamaProje.Models.TownModel

@{
    Layout = "_LayoutAdmin";
    ViewData["Title"] = "Create";
}


<form asp-action="Create">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @_localization.GetKey("Create")
        </h1>
        <div class="float-right">
            <button type="submit" value="Save" class="btn btn-primary mt-3">@_localization.GetKey("Submit")</button>
            <a class="btn btn-secondary mt-3" asp-controller="Town" asp-action="Index">@_localization.GetKey("BackToList")</a>
        </div>
    </div>

    <div class="card">
        <div class="card-body">

            <div class="form-group col-md-12">
                <div class="form-group row">
                    <div class="col-md-4">
                        <label asp-for="Name">@_localization.GetKey("Name")</label>
                    </div>
                    <div class="col-md-8">
                        <input asp-for="Name" class="form-control" placeholder="@_localization.GetKey("Name")">
                    </div>
                </div>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group col-md-12">
                <div class="form-group row">
                    <div class="col-md-4">
                        <label asp-for="City">@_localization.GetKey("City")</label>
                    </div>
                    <div class="col-md-8">
                        <input asp-for="City" class="form-control" placeholder="@_localization.GetKey("City")">
                    </div>
                </div>
                <span asp-validation-for="City" class="text-danger"></span>
            </div>

            <div class="form-group col-md-12">
                <div class="form-group row">
                    <div class="col-md-4">
                        <label asp-for="Country">@_localization.GetKey("Country")</label>
                    </div>
                    <div class="col-md-8">
                        <input asp-for="Country" class="form-control" placeholder="@_localization.GetKey("Country")">
                    </div>
                </div>
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>

        </div>
    </div>
</form>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebProgramalamaProje/WebProgramalamaProje/Views/Town/Edit.cshtml
@model WebProgramalamaProje.Models.TownModel

@{
    Layout = "_LayoutAdmin";

    ViewData["Title"] = "Edit";
}


<form asp-action="Edit">

    <div class="content-header clearfix">
        <h1 class="float-left">
            @_localization.GetKey("Edit") - @Model.Id
        </h1>
        <div class="float-right">
            <button type="submit" value="Save" class="btn btn-primary mt-3">@_localization.GetKey("Submit")</button>
            <a class="btn btn-secondary mt-3" asp-controller="Town" asp-action="Index">@_localization.GetKey("BackToList")</a>
        </div>
    </div>

    <input type="hidden" asp-for="Id" />

    <div class="card">
        <div class="card-body">

            <div class="form-group col-md-12">
                <div class="form-group row">
                    <div class="col-md-4">
                        <label asp-for="Name">@_localization.GetKey("Name")</label>
                    </div>
                    <div class="col-md-8">
                        <input asp-for="Name" class="form-control" placeholder="@_localization.GetKey("Name")">
                    </div>
                </div>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group col-md-12">
                <div class="form-group row">
                    <div class="col-md-4">
                        <label asp-for="City">@_localization.GetKey("City")</label>
                    </div>
                    <div class="col-md-8">
                        <input asp-for="City" class="form-control" placeholder="@_localization.GetKey("City")">
                    </div>
                </div>
                <span asp-validation-for="City" class="text-danger"></span>
            </div>

            <div class="form-group col-md-12">
                <div class="form-group row">
                    <div class="col-md-4">
                        <label asp-for="Country">@_localization.GetKey("Country")</label>
                    </div>
                    <div class="col-md-8">
                        <input asp-for="Country" class="form-control" placeholder="@_localization.GetKey("Country")">
                    </div>
                </div>
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>

        </div>
    </div>
</form>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebProgramalamaProje/WebProgramalamaProje/Views/Town/Index.cshtml
@model List<WebProgramalamaProje.Models.TownModel>

@{
    Layout = "_LayoutAdmin";
    ViewData["Title"] = "Index";
}

<h1>@_localization.GetKey("TownIndexTitle")</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">@_localization.GetKey("Create")</a>
</p>
<div class="card">
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @_localization.GetKey("Name")
                    </th>
                    <th>
                        @_localization.GetKey("City")
                    </th>
                    <th>
                        @_localization.GetKey("Country")
                    </th>
                    <th>@_localization.GetKey("Edit") & @_localization.GetKey("Delete")</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr id="item-@item.Id">
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.City)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Country)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">@_localization.GetKey("Edit")</a>
                            <button class="delete-button btn btn-danger" data-id="@item.Id">@_localization.GetKey("Delete")</button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.delete-button').click(function () {
            var id = $(this).data('id');
            $.ajax({
                type: 'POST',
                url: '@Url.Action("Delete", "Town")',
                data: { id: id },
                success: function (response) {
                    if (response.success) {
                        $('#item-' + id).remove(); // Remove the item row from the table
                    } else {
                        // Handle failure
                    }
                }
            });
        });
    });
</script>