WebProgramalamaProje/WebProgramalamaProje/Controllers/ClinicController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebProgramalamaProje.Data;
using WebProgramalamaProje.Models;
using WebProgramalamaProje.Models.CombinedModels;

namespace WebProgramalamaProje.Controllers
{
    [Authorize(Roles = "Admin")]

    public class ClinicController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ClinicController(ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            var model = from clinic in _db.Clinics
                                        join hospital in _db.Hospital on clinic.HospitalId equals hospital.Id
                                        select new ClinicHospitalFieldsModel
                                        {
                                               Id = clinic.Id,
                                               Name = clinic.Name,
                                               HospitalName = hospital.Name,
                                        };
            var result=await model.ToListAsync();
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> List()
        {
            return View();
        }

        public async Task<IActionResult> Create()
        {
            ClinicHospitalModel model = new ClinicHospitalModel();
            model.Hospitals = await _db.Hospital.ToListAsync();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ClinicHospitalModel model)
        {
            if(model.Clinic != null)
            {
               await _db.Clinics.AddAsync(model.Clinic);
               await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View();
        }

        public async Task<IActionResult> Edit(int id)
        {
            ClinicHospitalModel model = new ClinicHospitalModel
            {
                Hospitals = await _db.Hospital.ToListAsync(),
                Clinic = await _db.Clinics.FindAsync(id),
                ClinicWorkTimes = await _db.ClinicWorkTimes.Where(a => a.ClinicId == id).ToListAsync(),
            };


            if (model.Clinic != null)
             return View(model);
            
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ClinicHospitalModel model)
        {
            if(model.Clinic != null)
            {
               _db.Clinics.Update(model.Clinic);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var model = await _db.Clinics.FindAsync(id);
            if (model != null)
            {
                _db.Clinics.Remove(model);
                await _db.SaveChangesAsync();

                return Json(new { success = true, deletedId = id });
            }
            return Json(new { error = true });
        }

    }
}

WebProgramalamaProje/WebProgramalamaProje/Views/Clinic/Create.cshtml
@model WebProgramalamaProje.Models.CombinedModels.ClinicHospitalModel;

@{
    Layout = "_LayoutAdmin";
    ViewData["Title"] = "Create";
}

<form asp-action="Create" method="post">

    <div class="content-header clearfix">
        <h1 class="float-left">
            @_localization.GetKey("Create")
        </h1>
        <div class="float-right">
            <button type="submit" value="Save" class="btn btn-primary mt-3">@_localization.GetKey("Submit")</button>
            <a class="btn btn-secondary mt-3" asp-controller="Clinic" asp-action="Index">@_localization.GetKey("BackToList")</a>
        </div>
    </div>

    <div class="card">
        <div class="card-body">

            <div class="form-group col-md-12">
                <div class="form-group row">
                    <div class="col-md-4">
                        <label asp-for="Clinic.Name">@_localization.GetKey("Name")</label>
                    </div>
                    <div class="col-md-8">
                        <input asp-for="Clinic.Name" class="form-control" placeholder="@_localization.GetKey("Name")">
                    </div>
                </div>
                <span asp-validation-for="Clinic.Name" class="text-danger"></span>
            </div>

            <div class="form-group col-md-12">
                <div class="form-group row">
                    <div class="col-md-4">
                        <label asp-for="Clinic.HospitalId">@_localization.GetKey("Hospital")</label>
                    </div>
                    <div class="col-md-8">
                        <select class="form-control" asp-for="Clinic.HospitalId">
                            @foreach (var hospital in Model.Hospitals)
                            {
                                <option value="@hospital.Id">@hospital.Name</option>
                            }
                        </select>
                    </div>
                </div>
                <span asp-validation-for="Clinic.HospitalId" class="text-danger"></span>
            </div>

        </div>
    </div>

</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebProgramalamaProje/WebProgramalamaProje/Views/Clinic/Edit.cshtml
@{
    Layout = "_LayoutAdmin";
    ViewData["Title"] = "Edit";
}

@model WebProgramalamaProje.Models.CombinedModels.ClinicHospitalModel;


<form asp-action="Edit" asp-controller="Clinic" method="post">

    <div class="content-header clearfix">
        <h1 class="float-left">
            @_localization.GetKey("Edit") @_localization.GetKey("Clinic") - @Model.Clinic.Id
        </h1>
        <div class="float-right">
            <button type="submit" value="Save" class="btn btn-primary mt-3">@_localization.GetKey("Submit")</button>
            <a class="btn btn-secondary mt-3" asp-controller="Clinic" asp-action="Index">@_localization.GetKey("BackToList")</a>
        </div>
    </div>

    <input asp-for="Clinic.Id" hidden/>

    <div class="card">
        <div class="card-body">

            <div class="form-group col-md-12">
                <div class="form-group row">
                    <div class="col-md-4">
                        <label asp-for="Clinic.Name">@_localization.GetKey("Name")</label>
                    </div>
                    <div class="col-md-8">
                        <input asp-for="Clinic.Name" class="form-control" placeholder="@_localization.GetKey("Name")">
                    </div>
                </div>
                <span asp-validation-for="Clinic.Name" class="text-danger"></span>
            </div>

            <div class="form-group col-md-12">
                <div class="form-group row">
                    <div class="col-md-4">
                        <label asp-for="Clinic.HospitalId">@_localization.GetKey("Hospital")</label>
                    </div>
                    <div class="col-md-8">
                        <select class="form-control" asp-for="Clinic.HospitalId">
                            @foreach (var hospital in Model.Hospitals)
                            {
                                <option value="@hospital.Id">@hospital.Name</option>
                            }
                        </select>
                    </div>
                </div>
                <span asp-validation-for="Clinic.HospitalId" class="text-danger"></span>
            </div>

        </div>
    </div>

</form>

<div class="card content-header ">
    <div class="float-right ">
        <h5 class="btn btn-info float-left">@_localization.GetKey("ClinicWorkTimes")</h5>
        <div class="float-right ">
            <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                @_localization.GetKey("ClinicWorkTimes")
            </a>
        </div>
    </div>

    <div class="card-body content-header">
        <div class="collapse" id="collapseExample">

            <div class="card card-body">
                @await Html.PartialAsync("../ClinicWorkTimes/_ClinicWorkTimes.cshtml",Model.ClinicWorkTimes)
            </div>
            <p>
                <a asp-controller="ClinicWorkTimes" asp-action="Create" asp-route-clinicId="@Model.Clinic.Id" class="btn btn-primary">@_localization.GetKey("Create")</a>
            </p>
        </div>

    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebProgramalamaProje/WebProgramalamaProje/Views/Clinic/Index.cshtml
@model List<WebProgramalamaProje.Models.CombinedModels.ClinicHospitalFieldsModel>;

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_LayoutAdmin";
    ViewData["Title"] = "Index";
}

<h1>@_localization.GetKey("ClinicIndexTitle")</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">@_localization.GetKey("Create")</a>
</p>
<div class="card">
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @_localization.GetKey("Clinic")
                    </th>
                    <th>
                        @_localization.GetKey("Hospital")
                    </th>
                    <th>@_localization.GetKey("Edit") & @_localization.GetKey("Delete")</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var clinic in Model)
                {
                    <tr id="item-@clinic.Id">
                        <td>
                            @clinic.Name
                        </td>
                        <td>
                            @clinic.HospitalName
                        </td>
                        <td>
                            <a class="btn btn-warning" asp-controller="Clinic" asp-route-id="@clinic.Id" asp-action="Edit">@_localization.GetKey("Edit")</a>
                            <button class="delete-button btn btn-danger" data-id="@clinic.Id">@_localization.GetKey("Delete")</button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.delete-button').click(function () {
            var id = $(this).data('id');
            $.ajax({
                type: 'POST',
                url: '@Url.Action("Delete", "Clinic")',
                data: { id: id },
                success: function (response) {
                    if (response.success) {
                        $('#item-' + id).remove(); // Remove the item row from the table
                    } else {
                        // Handle failure
                    }
                }
            });
        });
    });
</script>